# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: LoRa_P2P_Slave
# Can be C or C++
language: C

optimization: Og

# MCU settings
targetMCU: stm32wlx
cpu: cortex-m4 # type of cpu e.g. cortex-m4
fpu:  # Defines how floating points are defined. Can be left empty.
floatAbi: 
ldscript: STM32WLE5XX_FLASH.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions: 
  - USE_FULL_LL_DRIVER
  - CORE_CM4
  - USE_HAL_DRIVER
  - STM32WLE5xx

cxxDefinitions: 
  - USE_FULL_LL_DRIVER
  - CORE_CM4
  - USE_HAL_DRIVER
  - STM32WLE5xx

asDefinitions: []

# Compiler definition files. you can add a single files or an array of files for different definitions.
# The file is expected to have a definition each new line.
# This allows to include for example a .definition file which can be ignored in git and can contain
# This can be convenient for passing along secrets at compile time, or generating a file for per device setup.
cDefinitionsFile:
cxxDefinitionsFile:
asDefinitionsFile:

# Compiler flags
cFlags: []
cxxFlags: []
assemblyFlags: []
linkerFlags: 
  - -specs=nano.specs


# libraries to be included. The -l prefix to the library will be automatically added.
libraries: 
  - c
  - m
  - nosys

# Library directories. Folders can be added here that contain custom libraries.
libraryDirectories: []

# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes: 
  - "**/Examples/**"
  - "**/examples/**"
  - "**/Example/**"
  - "**/example/**"
  - "**_template.*"


# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories: 
  - Core/Inc
  - SubGHz_Phy/App
  - SubGHz_Phy/Target
  - Utilities/trace/adv_trace
  - Drivers/STM32WLxx_HAL_Driver/Inc
  - Drivers/STM32WLxx_HAL_Driver/Inc/Legacy
  - Utilities/misc
  - Utilities/sequencer
  - Utilities/timer
  - Utilities/lpm/tiny_lpm
  - Middlewares/Third_Party/SubGHz_Phy
  - Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver
  - Drivers/CMSIS/Device/ST/STM32WLxx/Include
  - Drivers/CMSIS/Include
  - Inc/**
  - Core/Inc/**
  - Core/Lib/**
  - Src/**
  - Core/Src/**
  - Core/Lib/**


# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:  
  - startup_stm32wle5xx.s
  - Core/Src/main.c
  - Core/Src/gpio.c
  - Core/Src/dma.c
  - Core/Src/i2c.c
  - Core/Src/rtc.c
  - Core/Src/subghz.c
  - Core/Src/stm32_lpm_if.c
  - Core/Src/sys_app.c
  - Core/Src/sys_debug.c
  - Core/Src/timer_if.c
  - Core/Src/usart_if.c
  - Core/Src/usart.c
  - Core/Src/stm32wlxx_it.c
  - Core/Src/stm32wlxx_hal_msp.c
  - SubGHz_Phy/Target/radio_board_if.c
  - SubGHz_Phy/App/app_subghz_phy.c
  - SubGHz_Phy/App/subghz_phy_app.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_utils.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_exti.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc_ex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash_ex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gpio.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma_ex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_exti.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rcc.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_i2c.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_gpio.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dma.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc_ex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim_ex.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.c
  - Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.c
  - Core/Src/system_stm32wlxx.c
  - Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver/radio_driver.c
  - Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver/radio_fw.c
  - Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver/radio.c
  - Utilities/trace/adv_trace/stm32_adv_trace.c
  - Utilities/misc/stm32_mem.c
  - Utilities/misc/stm32_systime.c
  - Utilities/misc/stm32_tiny_sscanf.c
  - Utilities/misc/stm32_tiny_vsnprintf.c
  - Utilities/sequencer/stm32_seq.c
  - Utilities/timer/stm32_timer.c
  - Utilities/lpm/tiny_lpm/stm32_lpm.c
  - Core/Src/lcd.c
  - Src/**
  - Core/Src/**
  - Core/Lib/**


# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: false

# Custom makefile rules
# Here custom makefile rules can be added to the STM32Make.make file
# an example of how this can be used is commented out below.
customMakefileRules:
# - command: sayhello
#   rule: echo "hello"
#   dependsOn: $(BUILD_DIR)/$(TARGET).elf # can be left out    
    